import chromium from "@sparticuz/chromium";
import puppeteer from "puppeteer-core";

export const maxDuration = 60;
export const runtime = "nodejs";

export async function POST(req: Request) {
  try {
    const data = await req.json();

    const { score, status, country, type, sources } = data;

const executablePath = await chromium.executablePath();

const browser = await puppeteer.launch({
  args: [...chromium.args, "--no-sandbox", "--disable-setuid-sandbox"],
  executablePath: executablePath || undefined,
  headless: true,
});


    const page = await browser.newPage();

    // 🎨 Status color
    let color = "green";
    if (status === "Suspicious") color = "orange";
    if (status === "Malicious") color = "red";

    // 🧠 Explanation
    const explanation =
      status === "Safe"
        ? "No significant malicious activity detected."
        : status === "Suspicious"
        ? "Suspicious indicators found. Further investigation recommended."
        : "Highly malicious indicator. Immediate action required.";

    // 📄 HTML content
    const html = `
      <html>
        <body style="font-family: Arial; padding: 20px;">
          <h1>SentinelScope Threat Report</h1>

          <p><strong>Type:</strong> ${type}</p>
          <p><strong>Country:</strong> ${country}</p>
          <p><strong>Score:</strong> ${score}</p>
          <p style="color:${color}; font-weight:bold;">Status: ${status}</p>

          <h3>Threat Sources</h3>
          <p>VirusTotal: ${sources?.vtMalicious || 0}</p>
          <p>AbuseIPDB: ${sources?.abuseScore || 0}</p>
          <p>OTX Pulses: ${sources?.otxPulses || 0}</p>

          <h3>Analysis</h3>
          <p>${explanation}</p>

          <h3>Recommendations</h3>
          <ul>
            <li>Block if malicious</li>
            <li>Monitor traffic</li>
            <li>Investigate endpoints</li>
          </ul>

          <p style="margin-top:30px;">Generated by SentinelScope</p>
        </body>
      </html>
    `;

    // 🧠 Proper render wait
    await page.setContent(html, {
      waitUntil: "networkidle0",
    });

    await new Promise((resolve) => setTimeout(resolve, 500));

    // 📄 Generate PDF (ONLY ONE declaration)
    const pdfBuffer = await page.pdf({
      format: "A4",
      printBackground: true,
    });

    await browser.close();

    return new Response(pdfBuffer as unknown as BodyInit, {
      headers: {
        "Content-Type": "application/pdf",
        "Content-Disposition": "attachment; filename=report.pdf",
      },
    });
  } catch (error) {
    return new Response(
      JSON.stringify({ error: "PDF generation failed" }),
      { status: 500 }
    );
  }
}