import { NextResponse } from "next/server";
import html_to_pdf from "html-pdf-node";

export const runtime = "nodejs";

export async function POST(req: Request) {
  try {
    const data = await req.json();

    const { score, status, country, type, sources } = data;

    let color = "green";
    if (status === "Suspicious") color = "orange";
    if (status === "Malicious") color = "red";

    const explanation =
      status === "Safe"
        ? "No significant malicious activity detected."
        : status === "Suspicious"
        ? "Suspicious indicators found. Further investigation recommended."
        : "Highly malicious indicator. Immediate action required.";

    const html = `
      <html>
        <body style="font-family: Arial; padding: 20px;">
          <h1>SentinelScope Threat Report</h1>

          <p><strong>Type:</strong> ${type}</p>
          <p><strong>Country:</strong> ${country}</p>
          <p><strong>Score:</strong> ${score}</p>
          <p style="color:${color}; font-weight:bold;">Status: ${status}</p>

          <h3>Threat Sources</h3>
          <p>VirusTotal: ${sources?.vtMalicious || 0}</p>
          <p>AbuseIPDB: ${sources?.abuseScore || 0}</p>
          <p>OTX Pulses: ${sources?.otxPulses || 0}</p>

          <h3>Analysis</h3>
          <p>${explanation}</p>

          <h3>Recommendations</h3>
          <ul>
            <li>Block if malicious</li>
            <li>Monitor traffic</li>
            <li>Investigate endpoints</li>
          </ul>

          <p style="margin-top:30px;">Generated by SentinelScope</p>
        </body>
      </html>
    `;

    const file = { content: html };

    const pdfBuffer = await html_to_pdf.generatePdf(file, {
      format: "A4",
    });

    return new NextResponse(pdfBuffer, {
      headers: {
        "Content-Type": "application/pdf",
        "Content-Disposition": "attachment; filename=report.pdf",
      },
    });
  } catch (error) {
    return NextResponse.json(
      { error: "PDF generation failed" },
      { status: 500 }
    );
  }
}