import chromium from "chrome-aws-lambda";
import puppeteer from "puppeteer-core";

export const runtime = "nodejs";

export async function POST(req: Request) {
  const data = await req.json();

  const { score, status, country, type, sources } = data;

  const executablePath = await chromium.executablePath;

  const browser = await puppeteer.launch({
    args: chromium.args,
    executablePath: executablePath || undefined,
    headless: true,
  });

  const page = await browser.newPage();

  let color = "green";
  if (status === "Suspicious") color = "orange";
  if (status === "Malicious") color = "red";

  const explanation = `
    ${
      status === "Safe"
        ? "No significant malicious activity detected."
        : status === "Suspicious"
        ? "Suspicious indicators found. Further investigation recommended."
        : "Highly malicious indicator. Immediate action required."
    }
  `;

  await page.setContent(`
    <html>
      <body style="font-family: Arial; padding: 20px;">
        <h1>SentinelScope Threat Report</h1>

        <p><strong>Type:</strong> ${type}</p>
        <p><strong>Country:</strong> ${country}</p>
        <p><strong>Score:</strong> ${score}</p>
        <p style="color:${color}; font-weight:bold;">Status: ${status}</p>

        <h3>Threat Sources</h3>
        <p>VirusTotal: ${sources?.vtMalicious || 0}</p>
        <p>AbuseIPDB: ${sources?.abuseScore || 0}</p>
        <p>OTX Pulses: ${sources?.otxPulses || 0}</p>

        <h3>Analysis</h3>
        <p>${explanation}</p>

        <h3>Recommendations</h3>
        <ul>
          <li>Block if malicious</li>
          <li>Monitor traffic</li>
          <li>Investigate endpoints</li>
        </ul>

        <p style="margin-top:30px;">Generated by SentinelScope</p>
      </body>
    </html>
  `);

  const pdf = await page.pdf({ format: "A4" });

  await browser.close();

  return new Response(pdf as unknown as BodyInit, {
    headers: {
      "Content-Type": "application/pdf",
      "Content-Disposition": "attachment; filename=report.pdf",
    },
  });
}